title: Chronicle Destiny
description: Documentation for Chronicle Destiny

remote_theme: BlueStar03/theme@v3.0.0

toc-include-h1: true

colors:
  accent:    "#6495ed"   # link/buttons highlight

nav:
  - title: ğŸ  Home
    url: /

plugins:
  - jekyll-remote-theme

nav:
  - title: ğŸ  Home
    url: /
  - title: ğŸ“ Changelog
    url: /changelog

