title: Chronicle Destiny
description: Documentation for Chronicle Destiny

remote_theme: BlueStar03/theme@v2.0.0

toc-include-h1: true

colors:
  accent:    "#6495ed"   # link/buttons highlight

nav:
  - title: üè† Home
    url: /

plugins:
  - jekyll-remote-theme
